name: "Corne Ultralight Nice Nano v2 Nice View VI Nav"
on: workflow_dispatch
jobs:
    build:
        uses: ./.github/workflows/main.yml
        secrets: inherit
        with:
            board: '["nice_nano_v2"]'
            shield: '["corne_left nice_view_adapter nice_view","corne_right nice_view_adapter nice_view"]'
            nav: '["vi"]'
            kconfig: '["CONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_SLEEP=y\nCONFIG_ZMK_EXT_POWER=y\nCONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y\nCONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y\nCONFIG_BT_CTLR_TX_PWR_MINUS_20=y\nCONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y"]'
            alphas: '["QWERTY"]'
            custom_config: '["#define MIRYOKU_TAP_QWERTY"]'
